PREFIX oboInOwl: <http://www.geneontology.org/formats/oboInOwl#>

select *
where {
    VALUES ?p {
        oboInOwl:hasAlternativeId
        oboInOwl:hasDbXref
    }
    ?s ?p ?o .
}
#LIMIT 1000000
#OFFSET 3000000