PREFIX dct: <http://purl.org/dc/terms/>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

PREFIX cso: <http://cso.kmi.open.ac.uk/schema/cso#>
PREFIX topic: <https://cso.kmi.open.ac.uk/topics/>


SELECT DISTINCT ?dbpedia
WHERE {
    ?t a cso:Topic .

    OPTIONAL {
        ?t owl:sameAs ?dbpedia .
        FILTER(STRSTARTS(STR(?dbpedia), 'http://dbpedia.org/'))
    }

    OPTIONAL {
        ?t owl:sameAs ?wikidata .
        FILTER(STRSTARTS(STR(?wikidata), 'http://www.wikidata.org/'))
    }

    # XOR
    FILTER((BOUND(?dbpedia) && !BOUND(?wikidata)) || !BOUND(?dbpedia) && BOUND(?wikidata))
}
