prefix skos: <http://www.w3.org/2004/02/skos/core#>
prefix cso: <http://cso.kmi.open.ac.uk/schema/cso#>

delete {
  ?s ?p ?o .
}

where {
  ?s cso:preferentialEquivalent ?eq .
  FILTER(?s != ?eq)
  
  ?s ?p ?o .
}