PREFIX dct: <http://purl.org/dc/terms/>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

PREFIX cso: <http://cso.kmi.open.ac.uk/schema/cso#>
PREFIX topic: <https://cso.kmi.open.ac.uk/topics/>

select (COUNT(DISTINCT ?t) as ?c)
where {
    ?t a cso:Topic ;
        owl:sameAs ?b .
    
    FILTER NOT EXISTS { ?b a cso:Topic } .
}

