PREFIX dct: <http://purl.org/dc/terms/>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

PREFIX cso: <http://cso.kmi.open.ac.uk/schema/cso#>
PREFIX topic: <https://cso.kmi.open.ac.uk/topics/>

PREFIX dbo: <http://dbpedia.org/ontology/>

PREFIX tmp: <https://localhost/cso_dbp/>


INSERT {
    ?dbpedia tmp:usedInCSO true .
}
WHERE {
    ?t a cso:Topic ;
        owl:sameAs ?dbpedia .

    FILTER(STRSTARTS(STR(?dbpedia), 'http://dbpedia.org/'))
}
